# Generated by Django 3.2.13 on 2022-06-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('course', models.CharField(max_length=200)),
                ('collage', models.CharField(max_length=200)),
            ],
        ),
    ]
